version: '3'

tasks:
  ci:
    cmds:
      - task: format
      - task: lint
      - task: build

  format:
    cmds:
      - dprint check
      - npx biome format .

  lint:
    cmds:
      - npx biome lint .

  build:
    cmds:
      - task: clean
      - npx tsc

  clean:
    cmds:
      - rm -rf dist
